categories:
- Data Managers
description: refgenie asset pulling from remote resource
homepage_url: http://refgenie.databio.org/
long_description: |
    This data manager enables Galaxy admins to pull remote refgenie resources into their locally configured refgenie installation.
name: data_manager_refgenie_pull
owner: blankenberglab
remote_repository_url: https://github.com/blankenberglab/galaxy-tools-blankenberg/tree/main/data_managers/data_manager_refgenie_pull
type: unrestricted
